image:
  file: .gitpod.Dockerfile

#ports:
  # MySQL server
  #- port: 3306
  #  onOpen: ignore

# exposed ports
ports:
- port: 8080
  onOpen: open-preview


vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack
    - yzhang.markdown-all-in-one
    - stevennyang.database-modeling-markdown
    - sohibe.java-generate-setters-getters


tasks:
  - init: >
      mysql -u root -e "create database example_app" &&
      mysql -u root -p example_app < createTables.sql &&
      mysql -u root -p example_app < insertData.sql &&
      ./mvnw -B dependency:go-offline package -DskipTests
    
    command: java -jar target/*.jar
    name: Run Employee SpringBoot
      
    #  cp .env.example .env &&
    # composer install
